# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lib\ui\MainWindowUi.ui'
#
# Created: Sun Mar 23 20:53:42 2014
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(700, 480)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setContentsMargins(-1, 0, 0, 0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.gb_video = QtGui.QGroupBox(self.centralwidget)
        self.gb_video.setObjectName(_fromUtf8("gb_video"))
        self.gridLayout_3 = QtGui.QGridLayout(self.gb_video)
        self.gridLayout_3.setMargin(1)
        self.gridLayout_3.setSpacing(1)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setSpacing(2)
        self.gridLayout_2.setContentsMargins(-1, -1, 0, -1)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 5, -1, -1)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lbl_frame_time = QtGui.QLabel(self.gb_video)
        self.lbl_frame_time.setObjectName(_fromUtf8("lbl_frame_time"))
        self.horizontalLayout.addWidget(self.lbl_frame_time)
        self.scrollbar_time = QtGui.QScrollBar(self.gb_video)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollbar_time.sizePolicy().hasHeightForWidth())
        self.scrollbar_time.setSizePolicy(sizePolicy)
        self.scrollbar_time.setOrientation(QtCore.Qt.Horizontal)
        self.scrollbar_time.setInvertedAppearance(False)
        self.scrollbar_time.setInvertedControls(True)
        self.scrollbar_time.setObjectName(_fromUtf8("scrollbar_time"))
        self.horizontalLayout.addWidget(self.scrollbar_time)
        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.gv_video = GraphicsView(self.gb_video)
        self.gv_video.setObjectName(_fromUtf8("gv_video"))
        self.gridLayout_2.addWidget(self.gv_video, 0, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.lbl_frame_num = QtGui.QLabel(self.gb_video)
        self.lbl_frame_num.setObjectName(_fromUtf8("lbl_frame_num"))
        self.horizontalLayout_2.addWidget(self.lbl_frame_num)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label_3 = QtGui.QLabel(self.gb_video)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_2.addWidget(self.label_3)
        self.spin_bin_thresh = QtGui.QSpinBox(self.gb_video)
        self.spin_bin_thresh.setFocusPolicy(QtCore.Qt.NoFocus)
        self.spin_bin_thresh.setInputMethodHints(QtCore.Qt.ImhNone)
        self.spin_bin_thresh.setKeyboardTracking(False)
        self.spin_bin_thresh.setMaximum(255)
        self.spin_bin_thresh.setProperty("value", 20)
        self.spin_bin_thresh.setObjectName(_fromUtf8("spin_bin_thresh"))
        self.horizontalLayout_2.addWidget(self.spin_bin_thresh)
        self.ckb_bin_thresh = QtGui.QCheckBox(self.gb_video)
        self.ckb_bin_thresh.setObjectName(_fromUtf8("ckb_bin_thresh"))
        self.horizontalLayout_2.addWidget(self.ckb_bin_thresh)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 3, 0, 1, 1)
        self.gridLayout.addWidget(self.gb_video, 0, 0, 1, 1)
        self.toolBox = QtGui.QToolBox(self.centralwidget)
        self.toolBox.setMinimumSize(QtCore.QSize(200, 0))
        self.toolBox.setMaximumSize(QtCore.QSize(200, 16777215))
        self.toolBox.setObjectName(_fromUtf8("toolBox"))
        self.page = QtGui.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 200, 351))
        self.page.setObjectName(_fromUtf8("page"))
        self.verticalLayout = QtGui.QVBoxLayout(self.page)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setSpacing(2)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.gv_detail = GraphicsView(self.page)
        self.gv_detail.setObjectName(_fromUtf8("gv_detail"))
        self.gridLayout_4.addWidget(self.gv_detail, 0, 0, 1, 1)
        self.listWidget = QtGui.QListWidget(self.page)
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)
        self.gridLayout_4.addWidget(self.listWidget, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_4)
        self.toolBox.addItem(self.page, _fromUtf8(""))
        self.page_2 = QtGui.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 200, 351))
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.toolBox.addItem(self.page_2, _fromUtf8(""))
        self.gridLayout.addWidget(self.toolBox, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 700, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setEnabled(True)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.action_Quit = QtGui.QAction(MainWindow)
        self.action_Quit.setObjectName(_fromUtf8("action_Quit"))
        self.action_Open = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/Devine Icon 2/PNG/Black/Video.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Open.setIcon(icon)
        self.action_Open.setObjectName(_fromUtf8("action_Open"))
        self.action_Play = QtGui.QAction(MainWindow)
        self.action_Play.setCheckable(True)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/Devine Icon 2/PNG/Black/Play.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/Devine Icon 2/PNG/Black/Play.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/Devine Icon 2/PNG/Black/Play.png")), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.action_Play.setIcon(icon1)
        self.action_Play.setObjectName(_fromUtf8("action_Play"))
        self.actionPause = QtGui.QAction(MainWindow)
        self.actionPause.setCheckable(True)
        self.actionPause.setEnabled(False)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/Devine Icon 2/PNG/Black/Pause.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPause.setIcon(icon2)
        self.actionPause.setObjectName(_fromUtf8("actionPause"))
        self.actionRepeat = QtGui.QAction(MainWindow)
        self.actionRepeat.setCheckable(True)
        self.actionRepeat.setChecked(True)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/Devine Icon 2/PNG/Black/Repeat.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRepeat.setIcon(icon3)
        self.actionRepeat.setObjectName(_fromUtf8("actionRepeat"))
        self.actionRewind = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/Devine Icon 2/PNG/Black/Previous Track.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRewind.setIcon(icon4)
        self.actionRewind.setObjectName(_fromUtf8("actionRewind"))
        self.actionFastForward = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/Devine Icon 2/PNG/Black/Next Track.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFastForward.setIcon(icon5)
        self.actionFastForward.setObjectName(_fromUtf8("actionFastForward"))
        self.actionShow_Mask = QtGui.QAction(MainWindow)
        self.actionShow_Mask.setCheckable(True)
        self.actionShow_Mask.setObjectName(_fromUtf8("actionShow_Mask"))
        self.menuFile.addAction(self.action_Open)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action_Quit)
        self.menuView.addAction(self.actionShow_Mask)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.toolBar.addAction(self.action_Play)
        self.toolBar.addAction(self.actionPause)
        self.toolBar.addAction(self.actionRepeat)
        self.toolBar.addAction(self.actionRewind)
        self.toolBar.addAction(self.actionFastForward)

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MausVerPyler", None))
        self.gb_video.setTitle(_translate("MainWindow", "[No Video]", None))
        self.lbl_frame_time.setText(_translate("MainWindow", "00:00:00.000", None))
        self.lbl_frame_num.setText(_translate("MainWindow", "Frame 0/0", None))
        self.label_3.setText(_translate("MainWindow", "Binary Threshold:", None))
        self.ckb_bin_thresh.setText(_translate("MainWindow", "Show Mask", None))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("MainWindow", "testProperty", None))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("MainWindow", "Page 1", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("MainWindow", "Page 2", None))
        self.menuFile.setTitle(_translate("MainWindow", "&File", None))
        self.menuView.setTitle(_translate("MainWindow", "View", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.action_Quit.setText(_translate("MainWindow", "&Quit", None))
        self.action_Open.setText(_translate("MainWindow", "&Open", None))
        self.action_Open.setShortcut(_translate("MainWindow", "Ctrl+O", None))
        self.action_Play.setText(_translate("MainWindow", "&Play", None))
        self.action_Play.setToolTip(_translate("MainWindow", "Start playback", None))
        self.action_Play.setShortcut(_translate("MainWindow", "Ctrl+P", None))
        self.actionPause.setText(_translate("MainWindow", "Pause", None))
        self.actionPause.setToolTip(_translate("MainWindow", "Pause playback", None))
        self.actionPause.setShortcut(_translate("MainWindow", "Space", None))
        self.actionRepeat.setText(_translate("MainWindow", "Repeat", None))
        self.actionRepeat.setToolTip(_translate("MainWindow", "Repeat video on loop", None))
        self.actionRewind.setText(_translate("MainWindow", "Rewind", None))
        self.actionRewind.setToolTip(_translate("MainWindow", "Rewind video to start", None))
        self.actionFastForward.setText(_translate("MainWindow", "FastForward", None))
        self.actionFastForward.setToolTip(_translate("MainWindow", "Fast Forward to end of video", None))
        self.actionShow_Mask.setText(_translate("MainWindow", "Show &Mask", None))
        self.actionShow_Mask.setToolTip(_translate("MainWindow", "Show thresholding mask", None))
        self.actionShow_Mask.setShortcut(_translate("MainWindow", "Ctrl+M", None))

from lib.pyqtgraph import GraphicsView
import icons_rc
